# Generated by Django 2.1.7 on 2019-04-06 15:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='video',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='Video_ID',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
    ]
