# Generated by Django 2.1.7 on 2019-04-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videouploadmodel',
            name='videoFile',
            field=models.FileField(upload_to=''),
        ),
    ]
